version: "3"
services:
  app:
    image: ${IMAGE_NAME}
    container_name: ${PROJECT_NAME}-${COLOR}
    ports:
      - "${PORT}:8080"
    restart: always
    env_file:
      - .env.production
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
